# Pandas simplest demo


Hint: run cell: Shift+Enter

In [2]:
import pandas as pd

In [4]:
# Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)

In [5]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [6]:
df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [10]:
print(df['Age'].mean())

30.0

In [12]:
# Select people older than 28
older_than_28 = df[df['Age'] > 28]
older_than_28

      Name  Age    City
1      Bob   30  London
2  Charlie   35   Paris

In [13]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [15]:
df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [16]:
df['Age'] > 28

0    False
1     True
2     True
Name: Age, dtype: bool

In [17]:
df[df['Age'] > 28]

      Name  Age    City
1      Bob   30  London
2  Charlie   35   Paris