In [7]:
import pandas as pd

df = pd.DataFrame({
    "age": [25, 30, 45],
    "mail": ["alice@example.com", "bob@example.com", "carol@example.com"],
    "salaray": [50000, 60000, 80000]
})

df

   age               mail  salaray
0   25  alice@example.com    50000
1   30    bob@example.com    60000
2   45  carol@example.com    80000

In [8]:
df.set_index('mail', inplace=True)
df

                   age  salaray
mail
alice@example.com   25    50000
bob@example.com     30    60000
carol@example.com   45    80000

In [10]:
df.loc['alice@example.com']

age           25
salaray    50000
Name: alice@example.com, dtype: int64

In [15]:
df.iloc[:,1]

mail
alice@example.com    50000
bob@example.com      60000
carol@example.com    80000
Name: salaray, dtype: int64

In [16]:
df

                   age  salaray
mail
alice@example.com   25    50000
bob@example.com     30    60000
carol@example.com   45    80000